### ISSUE TITLE
0publish cant validate xz compressed archives

### ISSUE THREAD

**Issue by pmiess** [0install/0publish-win#28]
When attempting to validate a xz compressed tar archive 0publish posts an error that another process is accessing the file

http://repo.msys2.org/mingw/i686/mingw-w64-i686-mpc-1.1.0-1-any.pkg.tar.xz

![error 0](https://user-images.githubusercontent.com/7431414/89691236-6f4ade80-d8d6-11ea-8ef8-196ddd15cf49.png)

**Comment by bastianeicher** [comment]
Thanks for reporting this!

Fixed in 0install/0install-dotnet@f0cfce6ea275fbe9f63f5052d1b414163b343fc9. Will post here once there's a new released version.

**Comment by bastianeicher** [comment]
Fixed in [Zero Install Publishing Tools 2.18.1](https://github.com/0install/0publish-win/releases/2.18.1) and [Zero Install for Windows 2.18.1](https://github.com/0install/0install-win/releases/2.18.1).
