### ISSUE TITLE
wizard cant handle rar file

### ISSUE THREAD

**Issue by pmiess** [0install/0publish-win#29]
0publish says the following rar archive is invalid, 7zip opens it without error.
https://www.legroom.net/files/software/uniextract161_noinst.rar

**Comment by bastianeicher** [comment]
The archive in question is a RAR "solid" archive. The extraction failed because Zero Install did not support those yet. I've added support for this in 0install/0install-dotnet@da638e153352de1fdb6ec5d5aa79bad232f9872d.

**Comment by bastianeicher** [comment]
Fixed in [Zero Install Publishing Tools 2.18.1](https://github.com/0install/0publish-win/releases/2.18.1) and [Zero Install for Windows 2.18.1](https://github.com/0install/0install-win/releases/2.18.1).
