### ISSUE TITLE
0publish creates invalid XML files with duplicate ID's

### ISSUE THREAD

**Issue by pmiess** [0install/0publish-win#9]
After creating an implementation with an archive and pushing the add missing button the ID of the implementation is set to "sha1new="
If you are creating more than one implementation this creates an invalid XML since id's must be unique.

This may be related to the change that removed the sha1new and sha526 properties from the manifest-digest element.

I expect that 0publish should not create invalid XML or at least warn you if your saving an invalid XML file it created. 
Feeds with duplicate ID's cause 0install to be unable to find the implementation for the duplicate node.

**Comment by bastianeicher** [comment]
You are right, 853bbfa introduced this bug and was released as part of v2.14.2.
This is already fixed in ccd535e which will be released as part of v2.14.3 soon.
Until then you can run an older version as workaround:

    0install run --version=2.13.0 http://0install.de/feeds/ZeroInstall_Tools.xml

**Comment by bastianeicher** [comment]
Zero Install Publishing Tools 2.14.3 has been released. You can get it like this:

    0install update http://0install.de/feeds/ZeroInstall_Tools.xml
